### ISSUE TITLE
Always crash when click "add physical disk"

### ISSUE THREAD

**Issue by ToomsDK** [TalAloni/iSCSIConsole#8]
![Error1](https://user-images.githubusercontent.com/35465610/165835714-952a48ac-7375-43f7-a418-d865ebc2fd8b.gif)

Always crash when click "add physical disk"

Get this error every time, can it not just skip disk with errors and then show others 

---------------------------
Exception: System.IO.IOException: Failed to get disk 0 online status, Win32 Error: 32 Source: ISCSIConsole    at DiskAccessLibrary.Win32.PhysicalDisk.GetOnlineStatus(Boolean& isReadOnly)
   at ISCSIConsole.SelectPhysicalDiskForm.SelectPhysicalDiskForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

same error with 1.5.1 and 1.5.2

**Comment by TalAloni** [comment]
Thank you, I will look into it when I'll have time

**Comment by wisperC4** [comment]
hello, i'm in the same situation
win11 , try to mount a volume on physical disk 0 ( c:\ , d:\ e:\  3 partitions, trying to mount e: or d: is crashing , c: is windows system, do not touch it.
Regards

**Comment by wisperC4** [comment]
i can mount it with read only flag, i think windows lock in write this volume

**Comment by TalAloni** [comment]
wisperC4. this is not the same situation, in your case you can see the list of physical disks unlike the issue the OP reported.
Adding a physical disk for write access require that the disk will be available for the exclusive use of the program (i.e. no mounted volumes)

**Comment by Gerry546** [comment]
I can confirm that this problem is not only on Win11, I ran into this problem today as well (windows 11) and also tried it on two windows 10 systems. One did have a problem (company laptop, more restrictive policies likely) and my home pc. On my homepc it seems to work like a charm.
So I guess it has something to do with specific policies being active or not?

**Comment by june-park-stradvision** [comment]
same error 1.5.4 ;)

**Comment by june-park-stradvision** [comment]
hello.
An exception occurs when try to connect an sdcard with two partitions (vfat and ext4) as a physical disk.

**Comment by june-park-stradvision** [comment]
How do I force an SD card to go offline?
diskpart does not allow me to change it to offline, stating, "The operation is not supported on removable media."

**Comment by Prowler1000** [comment]
Just wondering if there is any movement on this issue. I was working on a hardware project of mine when suddenly my RPi stopped booting, so I'd like to take a look at the SD card contents.

I definitely don't mind looking into it, I was just wondering if you had done any work/diagnosis that I could continue from

**Comment by TalAloni** [comment]
Hi, I don't usually work with SD Cards and don't have one handy to test.

**Comment by Prowler1000** [comment]
That's totally fair! Even without the SD card though, I'm getting the same crashing that others were facing. (I mean, I think, I didn't read _every_ single word of the crash message)

I managed to mount and fix my SD card another way but I'd still be happy to look into this crash if you'd like, especially since I'm able to reproduce it!

**Comment by TalAloni** [comment]
I suspect the "get online status" should be skipped for SD cards, you're welcome to test this theory.
